--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

-- Started on 2022-06-24 16:32:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE portal_artikel;
--
-- TOC entry 3359 (class 1262 OID 16401)
-- Name: portal_artikel; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE portal_artikel WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'English_United States.1252';


ALTER DATABASE portal_artikel OWNER TO postgres;

\connect portal_artikel

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3360 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 837 (class 1247 OID 16417)
-- Name: enum_gender; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.enum_gender AS ENUM (
    'Pria',
    'Wanita'
);


ALTER TYPE public.enum_gender OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16444)
-- Name: komentar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komentar (
    id integer NOT NULL,
    konten text NOT NULL,
    user_id integer NOT NULL,
    postingan_id integer NOT NULL
);


ALTER TABLE public.komentar OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16443)
-- Name: komen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.komentar ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.komen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16431)
-- Name: postingan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.postingan (
    id integer NOT NULL,
    waktu_dibuat timestamp without time zone,
    konten text NOT NULL,
    lokasi character varying,
    user_id integer NOT NULL,
    judul character varying NOT NULL
);


ALTER TABLE public.postingan OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16430)
-- Name: postingan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.postingan ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.postingan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16413)
-- Name: profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profile (
    id integer NOT NULL
);


ALTER TABLE public.profile OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16412)
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16438)
-- Name: profilee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profilee (
    id integer NOT NULL,
    gender boolean NOT NULL,
    no_telp character varying,
    tanggal_lahir date,
    tempat_lahir character varying,
    bio character varying,
    user_id integer NOT NULL
);


ALTER TABLE public.profilee OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16437)
-- Name: profilee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.profilee ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.profilee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16402)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    nik character varying NOT NULL,
    name character varying NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16405)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3353 (class 0 OID 16444)
-- Dependencies: 218
-- Data for Name: komentar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.komentar (id, konten, user_id, postingan_id) FROM stdin;
\.


--
-- TOC entry 3349 (class 0 OID 16431)
-- Dependencies: 214
-- Data for Name: postingan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.postingan (id, waktu_dibuat, konten, lokasi, user_id, judul) FROM stdin;
\.


--
-- TOC entry 3347 (class 0 OID 16413)
-- Dependencies: 212
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profile (id) FROM stdin;
\.


--
-- TOC entry 3351 (class 0 OID 16438)
-- Dependencies: 216
-- Data for Name: profilee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profilee (id, gender, no_telp, tanggal_lahir, tempat_lahir, bio, user_id) FROM stdin;
\.


--
-- TOC entry 3344 (class 0 OID 16402)
-- Dependencies: 209
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, nik, name, email, password) FROM stdin;
\.


--
-- TOC entry 3361 (class 0 OID 0)
-- Dependencies: 217
-- Name: komen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.komen_id_seq', 1, false);


--
-- TOC entry 3362 (class 0 OID 0)
-- Dependencies: 213
-- Name: postingan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.postingan_id_seq', 1, false);


--
-- TOC entry 3363 (class 0 OID 0)
-- Dependencies: 211
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, false);


--
-- TOC entry 3364 (class 0 OID 0)
-- Dependencies: 215
-- Name: profilee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.profilee_id_seq', 1, false);


--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 210
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 3200 (class 2606 OID 16471)
-- Name: komentar komen_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komentar
    ADD CONSTRAINT komen_pk PRIMARY KEY (id);


--
-- TOC entry 3194 (class 2606 OID 16464)
-- Name: postingan postingan_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.postingan
    ADD CONSTRAINT postingan_pk PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 16453)
-- Name: profilee profilee_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profilee
    ADD CONSTRAINT profilee_pk PRIMARY KEY (id);


--
-- TOC entry 3189 (class 2606 OID 16455)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- TOC entry 3191 (class 2606 OID 16457)
-- Name: users users_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_un UNIQUE (id);


--
-- TOC entry 3198 (class 1259 OID 16449)
-- Name: komen_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX komen_id_idx ON public.komentar USING btree (id);


--
-- TOC entry 3192 (class 1259 OID 16450)
-- Name: postingan_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX postingan_id_idx ON public.postingan USING btree (id);


--
-- TOC entry 3195 (class 1259 OID 16451)
-- Name: profilee_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX profilee_id_idx ON public.profilee USING btree (id);


--
-- TOC entry 3187 (class 1259 OID 16411)
-- Name: users_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_id_idx ON public.users USING btree (id);


--
-- TOC entry 3203 (class 2606 OID 16472)
-- Name: komentar komen_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komentar
    ADD CONSTRAINT komen_fk FOREIGN KEY (id) REFERENCES public.postingan(id);


--
-- TOC entry 3204 (class 2606 OID 16477)
-- Name: komentar komen_fk2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komentar
    ADD CONSTRAINT komen_fk2 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 3201 (class 2606 OID 16465)
-- Name: postingan postingan_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.postingan
    ADD CONSTRAINT postingan_fk FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 3202 (class 2606 OID 16458)
-- Name: profilee profilee_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profilee
    ADD CONSTRAINT profilee_fk FOREIGN KEY (id) REFERENCES public.users(id);


-- Completed on 2022-06-24 16:32:46

--
-- PostgreSQL database dump complete
--

